{% set name = "pyposeidon" %}
{% set version = "0.6.0" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ec-jrc/pyPoseidon/archive/{{ version }}.tar.gz
  sha256: 89a975a60af560ffd3c645056cca530961f6fefd5541cd042052d4159abec093

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - pip
    - python >=3.6
    - setuptools
    - poetry
    - poetry-core
  run:
    - python >=3.6
    - mayavi
    - pyresample
    - pygeos >=0.7.1
    - geoviews
    - rasterio
    - jigsaw =0.9.12
    - hvplot
    - descartes
    - cfgrib <0.9.9
    - moviepy
    - colorlog
    - f90nml
    - zarr

test:
  imports:
    - pyposeidon

about:
  home: https://github.com/ec-jrc/pyPoseidon
  license: EUPL-1.2
  license_file: LICENSE
  summary: Framework for Hydrodynamic simulations

  # The remaining entries in this section are optional, but recommended.
  description: |
    pyPoseidon is a framework to setup, run and analyse geoflows.
    It warps around several solvers and is using python for the
    pre/post processing utilizing popular packages
    such as xarray, pandas, geopandas etc.
  doc_url: https://pyposeidon.readthedocs.io/
  dev_url: https://github.com/ec-jrc/pyPoseidon

extra:
  recipe-maintainers:
    - brey
    - pmav99
